name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: cd "src/Kull.DatabaseMetadata" && dotnet build -c Release
    - uses: actions/upload-artifact@v3
      with:
        name: Kull.DatabaseMetadata
        path: src/Kull.DatabaseMetadata/bin/Release/*.nupkg
    - uses: actions/upload-artifact@v3
      with:
        name: Kull.DatabaseMetadata-Symbol
        path: src/Kull.DatabaseMetadata/bin/Release/*.snupkg
